apiVersion: apps/v1
kind: Deployment
metadata:
  name: bootstrap       
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bootstrap
  template:
    metadata:
      labels:
        app: bootstrap
    spec:
      containers:
      - name: bootstrap
        image: mahesh2452/bootstrap:latest
        ports:
        - containerPort: 80   
---
apiVersion: v1
kind: Service
metadata:
  name: electro-service
spec:
  type: LoadBalancer
  selector:
    app: bootstrap
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
