apiVersion: apps/v1
kind: Deployment
metadata:
  name: electro-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: electro
  template:
    metadata:
      labels:
        app: electro
    spec:
      containers:
      - name: electro-container
        image: mahesh2452/bootstrap:latest
        ports:
        - containerPort: 80   
---
apiVersion: v1
kind: Service
metadata:
  name: electro-service
spec:
  type: LoadBalancer
  selector:
    app: electro
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
